// Builds src/styles/tokens.css from tokens/*.json (DTCG).
// One block per mode: :root (light + comfortable), .dark, [data-density="compact"].
// Mode blocks only contain tokens whose value differs from the default mode.
import fs from 'node:fs'
import StyleDictionary from 'style-dictionary'
import { transformGroups } from 'style-dictionary/enums'

const OUTPUT = 'src/styles/tokens.css'
const PRIMITIVES = 'tokens/primitive.json'
const SEMANTIC = 'tokens/semantic.json'

const transforms = StyleDictionary.hooks.transformGroups[transformGroups.css].map((t) =>
  t === 'size/rem' ? 'size/pxToRem' : t,
)

// Override blocks reference primitives defined in :root, which SD reports as "filtered out
// references"; that is intended, so warnings are only fatal for the base block.
async function buildBlock({ selector, include, source, filter }) {
  const sd = new StyleDictionary({
    include,
    source,
    log: { verbosity: 'default', warnings: filter ? 'disabled' : 'error' },
    platforms: {
      css: {
        transforms,
        prefix: 'ds',
        files: [
          {
            destination: 'block.css',
            format: 'css/variables',
            filter,
            options: { selector, outputReferences: true, showFileHeader: false },
          },
        ],
      },
    },
  })
  const [{ output }] = await sd.formatPlatform('css')
  const tokens = (await sd.getPlatformTokens('css')).allTokens
  return { output: output.trim(), tokens }
}

const originalValues = (tokens) =>
  new Map(tokens.map((t) => [t.name, JSON.stringify(t.original.$value)]))

const base = await buildBlock({
  selector: ':root',
  source: [PRIMITIVES, SEMANTIC, 'tokens/semantic.light.json', 'tokens/density.comfortable.json'],
})
const baseValues = originalValues(base.tokens)
const differsFromBase = (token) =>
  token.isSource && baseValues.get(token.name) !== JSON.stringify(token.original.$value)

const dark = await buildBlock({
  selector: '.dark',
  include: [PRIMITIVES, SEMANTIC],
  source: ['tokens/semantic.dark.json'],
  filter: differsFromBase,
})
const compact = await buildBlock({
  selector: '[data-density="compact"]',
  include: [PRIMITIVES, SEMANTIC],
  source: ['tokens/density.compact.json'],
  filter: differsFromBase,
})

const header = `/**
 * Generated by sd.config.js from tokens/*.json. Do not edit.
 * Run \`npm run build:tokens\` after changing tokens.
 */`
fs.writeFileSync(OUTPUT, [header, base.output, dark.output, compact.output].join('\n\n') + '\n')
console.log(`Wrote ${OUTPUT} (${base.tokens.length} base, dark + compact overrides)`)
