/**
 * Generated by sd.config.js from tokens/*.json. Do not edit.
 * Run `npm run build:tokens` after changing tokens.
 */

/** Durations in seconds, easings as cubic-bezier control points (Motion format). */
export const motion = {
  "duration": {
    "fast": 0.1,
    "base": 0.2,
    "slow": 0.3
  },
  "easing": {
    "standard": [0.2, 0, 0, 1],
    "enter": [0, 0, 0, 1],
    "exit": [0.3, 0, 1, 1]
  }
} as const
